### ISSUE TITLE
Suggestion: Multiple launch configurations.

### ISSUE THREAD

**Issue by Greg-76** [AlexMacocian/Daybreak#410]
Add the ability to setup multiple launch configurations with combinations between accounts and executables.
Add buttons for these configurations in the Game Companion view.

example in an image:
![Launch Account](https://github.com/AlexMacocian/Daybreak/assets/73719675/c649ac83-0e1d-4bdf-a9af-b830ffed3e4f)

**Comment by AlexMacocian** [comment]
This will go in before 0.9.0 beta release. It's a really good solution to managing multiple combinations of exe and accounts
